@local=http://localhost:3000/api

### 📥 Get All Positions
GET {{local}}/positions

### ➕ Add Position
POST {{local}}/positions
Content-Type: application/json

{
  "name": "employee"
}

### 🔄 Update Position
PUT {{local}}/positions
Content-Type: application/json

{
  "positionId": 3,
  "name": "emp",
  "description": "",
  "baseSalary": 0
}

### 🗑️ Remove Position
DELETE {{local}}/positions
Content-Type: application/json

{
  "positionId": 1
}
