export const ErrorMessages = {
  Auth: {
    USERNAME_EMPTY: 'Username must not be empty',
    PASSWORD_EMPTY: 'Password must not be empty',
    USERNAME_TOO_SHORT: 'Username must be at least 3 characters long',
    PASSWORD_TOO_SHORT: 'Password must be at least 6 characters long',
    ACCOUNT_ID_NOT_INTEGER: 'Account ID must be an integer',
    ACCOUNT_ID_TOO_SMALL: 'Account ID must be greater than 0',
  },
  account: {
    ACCOUNT_FALSE: 'Invalid username or password',
    ACCOUNT_NOT_FOUND: 'Account not found',
    ACCOUNT_USERNAME_EXISTS: 'Username already exists',
    USERNAME_EMPTY: 'Username must not be empty',
    PASSWORD_EMPTY: 'Password must not be empty',
    USERNAME_TOO_SHORT: 'Username must be at least 3 characters long',
    PASSWORD_TOO_SHORT: 'Password must be at least 6 characters long',
    ACCOUNT_ID_NOT_INTEGER: 'Account ID must be an integer',
    ACCOUNT_ID_TOO_SMALL: 'Account ID must be greater than 0',
    USERNAME_INVALID: 'Username must be a string',
    PASSWORD_INVALID: 'Password must be a string',
    USERNAME_ALL_NUMBER: 'Username must not be all numbers',
    ACOUNT_ALREADY_USE: 'Account is already in use',
  },
  position: {
    NAME_EMPTY: 'Position name must not be empty',
    NAME_INVALID: 'Position name must be a string',
    DESCRIPTION_INVALID: 'Description must be a string',
    BASE_SALARY_INVALID: 'Base salary must be a number',
    ID_NOT_INTEGER: 'Position ID must be an integer',
    ID_TOO_SMALL: 'Position ID must be greater than or equal to 1',
    POSITION_EXISTS: 'This position already exists',
    POSITION_NOT_FOUND: 'This position not found',
  },
  employee: {
    FULLNAME_EMPTY: 'Full name must not be empty',
    FULLNAME_INVALID: 'Full name must be a string',
    FULLNAME_ALL_NUMBER: 'Full name must not be all numbers',
    EMAIL_EMPTY: 'Email must not be empty',
    EMAIL_INVALID: 'Invalid email format',
    PHONE_NOT_STRING: 'Phone number must be a string',
    PHONE_INVALID: 'Phone number must be a valid Vietnamese number',
    ADDRESS_INVALID: 'Address must be a string',
    GENDER_INVALID: 'Gender must be Male, Female, or Other',
    DOB_INVALID: 'Date of birth must be a valid date',
    START_DATE_INVALID: 'Start date must be a valid date',
    IS_ACTIVE_INVALID: 'isActive must be a boolean',
    EMAIL_EXISTS: 'Email already exists',
    EMPLOYEE_NOT_FOUND: 'Employee not found',
    EMPLOYEE_EXISTS: 'Employee already exists',
    ID_NOT_INTEGER: 'Employee ID must be an integer',
    ID_TOO_SMALL: 'Employee ID must be greater than or equal to 1',
  },
  permission: {
    PERMISSION_EXISTS: 'Permission already exists',
    KEY_ALL_NUMBER: 'Key must not be all numbers',
    PERMISSION_NOT_FOUND: 'Permission not found',
    ID_NOT_INTEGER: 'Permission ID must be an integer',
    ID_TOO_SMALL: 'Permission ID must be greater than or equal to 1',
  },
  role: {
    ROLE_EXISTS: 'Role already exists',
    KEY_ALL_NUMBER: 'Key must not be all numbers',
    ROLE_NOT_FOUND: 'Role not found',
    ID_NOT_INTEGER: 'Role ID must be an integer',
    ID_TOO_SMALL: 'Role ID must be greater than or equal to 1',
  },
};
